### ISSUE TITLE
No image data on many dataset

### ISSUE THREAD

**Issue by dhthong92** [SpaceNetChallenge/utilities#119]
I've successfully downloaded the data given here https://spacenetchallenge.github.io/. It was fine with AOI_1_Rio dataset, but when I extracted AOI_2_Vegas and AOI_3_Paris, all I got is just a bunch of black images and all files have the same size as well. I've tried to unzip on both Ubuntu and Windows but still the same. Do I extract the dataset in the right way? Or could you re-check the hosted dataset? Many thanks!

**Comment by antran89** [comment]
I think we should eliminate those images from training set.

**Comment by nrweir** [comment]
The problem is likely not the images, but the software being used to open them. The images for Vegas, Paris, etc. are 16-bit TIFFs but the pixel values don't approach the 16-bit limit (65535). As a result, software that doesn't auto-scale to the image's bit range will display everything as black. CosmiQ has checked the posted images and confirmed that they contain image data. We recommend viewing the imagery with QGIS or another software tool intended for geospatial image data.
