### ISSUE TITLE
Utilities to rotate images and recompute the pixel-level bounding polygons. 

### ISSUE THREAD

**Issue by aurotripathy** [SpaceNetChallenge/utilities#3]
Hello:

I'm interested in augmenting the dataset via rotation. 

I want to start with the original untiled images, rotate them (from the center of the image), then retile them. Along with that step,  I'd like the pixel-level annotations for the bounding polygons to the adjusted accordingly. 

Will you make available utilities to rotate images and recompute the pixel-level bounding polygons.

-Auro

**Comment by dlindenbaum** [comment]
Hello Auro,

I think that should be possible.  It may take a couple of days but I will add it to the work list.

Dave

**Comment by toddstavish** [comment]
Awesome work! BTW, we are posting different approaches to analyzing Spacenet on our blog -The DownlinQ.  - https://medium.com/the-downlinq

**Comment by bakonzo** [comment]
Hello:

NEW Topcoder Challenge - Create Geospatial Computer Vision Algorithms with Real Satellite Data!
Geospatial Computer Vision Algorithms? Yes please!!!
1 11 November 2016 I got a pre-register invitation

This is not Spam, I would like you know that  I accept the invitation and for the reason that I am here I cannot compete even If I have this perspective of count up & running & working. My personal life has big influence on my behavior, the big obstacle on Amazon Cloud is that I cannot identify my self without a credit card,  I dont have a credit card so I cannot participate to the competition. And this make me so sad to have lost my chances. A closed door open one more big ...

So, come to my mind that maybe my suggestion can help you and other topcoder's to increasing your chances to victory following the right path on counting and storing file I develop.
It is  a smart change on observing perspective first, rather than pixel as second step. 
Me I  am fishing first, time is the second, wait 5s, loop 4 biometrical representation.

evaluateScene.py Today
    # initialize scene counts
    true_pos_counts = []
    false_pos_counts = []
    false_neg_counts = []

evaluateScene.py 1Atlas
    # initialize scene counts as pre-generated key
    true_pos_counts = [eye0]
    false_pos_counts = [eye1]
    false_neg_counts = [eye1]

eye is a stored file finite counter. 2 eye has two finite counters. parameters options:
all generated counter with match point on google earth and sky official project database.

eye0 has 1 eye Binary Value 0.
Key
0000 0000 0000 0000z 0 0 17 15 16 1597m 0 0 +Zed IP 12h0m49.20s 8 26 21.95.jpg

eye1 has 2 eye Binary Value 1.
Observe Key
0000 0000 0000 0000z 12h0m49.20s 8 26 21.95 0 0 17 15 16 1597m 0 0 +Zed IP.jpg
Reverse Key
0000 0000 0000 0000z 0 0 17 15 16 1597m 0 0 +Zed IP 12h0m49.20s 8 26 21.95.jpg

Matching Key
    Zed = Reverse Key
    0000 0000 0000 0000z 0 0 17 15 16 1597m 0 0 +Zed IP 12h0m49.20s 8 26 21.95.jpg
    
As we create the eye perspective, than like the dog do, set down its  nose and start to count (sniff). 0 and 1 are 5s listener getting parameters as key that it has finite counting.

    # load Truth and Test File Locations
    if len(sys.argv) > 1:
        truth_fp = sys.argv[1]
        test_fp = sys.argv[2]
    else:
        test_fp = sys.argv['../testData/public_polygons_solution_3Band_envelope.geojson']
        truth_fp = sys.argv['../testData/public_polygons_solution_3Band.geojson']
    
    ../testData/public_polygons_solution_3Band.geojson receive parameters on load/start, wait 5s for a call/signal.
    each .geojson moves in and within in a finite mode.

You are the server, Me I send parameters to you. 404 not found default that is the first degrees of perspective black in a cartesian canvas without images, than Each eye will paint itself.

writing this post as I told you before make me very sad, what I share with you above took 11 years to me on research and development, very deep and smart. it suck my bloody life, love velo levo, roma amor ra rab bar ... the counting I am suggestion to you is more than smart, it is IT what you are looking for neural geospatial exploration.

Lets look eye0

Default: http://1atlas.com/360/0000 0000 0000 0000z 0 0 17 15 16 1597m 0 0 +Zed IP.jpg
Going down: http://1atlas.com/360/0000 0000 0000 0000z 0 0 17 15 16 987m 0 0 +Zed IP.jpg
Going UP: http://1atlas.com/360/0000 0000 0000 0000z 0 0 17 15 16 2584m 0 0 +Zed IP.jpg
More UP: http://1atlas.com/360/0000 0000 0000 0000z 0 0 17 15 16 4181m 0 0 +Zed IP.jpg
up: http://1atlas.com/360/0000 0000 0000 0000z 0 0 17 15 16 6765m 0 0 +Zed IP 0.jpg
the same +1 Layer:  http://1atlas.com/360/0000 0000 0000 0000z 0 17 15 16 6765m 0 0 +Zed IP 1.jpg

The first block of 16/4 it embed etymology by scrambling (see next). all by count...

http://1atlas.com/360/0000 0000 0000 0000.jpg 
http://1atlas.com/360/1111 1111 1111 1111.jpg
http://1atlas.com/360/1111 1111 1111 1110.jpg
http://1atlas.com/360/1111 1111 1111 1101.jpg
http://1atlas.com/360/1111 1111 1111 1011.jpg
http://1atlas.com/360/1111 1111 1111 0111.jpg
http://1atlas.com/360/1111 1111 1110 1111.jpg
http://1atlas.com/360/1111 1111 1101 1111.jpg
[z,z,z]

if you curious on what I am telling you, than you can try to  roll the dice in a logical way and fish. 
For your test on roll the hebrew count 6, 12, 18, 22 from left to right on: http://www.2letterlookup.com/
two is the minimum, length is finite +1.

if not found or as the second option  here the best translator, just copy and paste from 2letterlookup.com on 
http://www.doitinhebrew.com/Translate/default.aspx?kb=IL+Hebrew+Phonetic

This way of counting it has support for in/out dynamic picto communication interchanging surfaces. It is the greatest adoption.

Is a POINTER CYPHER AlephBeth Crypto Binary DNA Storage

Cheers,
pp
