### ISSUE TITLE
Pascal format file can't be rightly converted

### ISSUE THREAD

**Issue by LokLu** [SpaceNetChallenge/utilities#40]
I try to use the createDataSpaceNet function to convert the original geojson to pascal format as the following command:

python python/createDataSpaceNet.py /media/lok/dataset/lok/data/spacenet/data/AOI_2_Vegas_Train/ \
	   --outputDirectory /media/lok/dataset/lok/data/spacenet/data/VOC/AOI_2_Vegas_Train/ \
           --convertTo8Bit 

It can work on AOI_3 and AOI_4 dataset. But when it comes to AOI_2 and AOI_5 dataset, the ground truth only contain at most one building footprint. The others are all missing. Can you help fix this bug?

Thanks for your time!

**Comment by mike-shvets** [comment]
Hello, in AOI_2_Vegas .geojson files appear to have "Id" field for each building object, which always equals 0. This gets interpreted by ogr module as if there is only one object (actually, the last one is being read). 

That being said, the issue is in the data format, not in the utilities. I temporarily fixed that by renaming "Id" field to "tmp_Id" in all .geojson files.

**Comment by LokLu** [comment]
@mike-shvets 
Hello Mike, tks for your reply. I found it was caused by the "Id". Currently, I remove all the ' "Id": 0,' string from geojson file. And it now works.

**Comment by dlindenbaum** [comment]
#47 Has some scripts that will show a way to clean the data.
